CREATE TABLE Books (
ID INT PRIMARY KEY,
Booktitle VARCHAR(50),
Author VARCHAR(25),
YEAR DATE);

INSERT INTO Books(ID,BookTitle,Author,YEAR)	 
 VALUES (1,'DAN BROWN','ALBERT','2024-08-01');

SELECT * FROM Books WHERE YEAR = '2024-08-01'; 