CREATE DATABASE SAMPLE;
USE SAMPLE

CREATE TABLE Books(
ID INT PRIMARY KEY,
BookTitle VARCHAR(50),
Author VARCHAR(50),
Year DATE  );

INSERT INTO Books(ID,BookTitle,Author,Year)
VALUES(1,'DAN','JAMES','2025-08-01');

INSERT INTO Books(ID,BookTitle,Author,Year)
VALUES (2,'ALCHAMIST','JAMES','2025-08-01'),
(3,'BEYOND THE LIFE' , 'JAM','2025-08-07');
SELECT * FROM Books WHERE Author != 'JAMES' ;
SELECT DISTINCT Author FROM Books;

ALTER TABLE Books ADD Email VARCHAR(25);
SELECT * FROM Books
UPDATE Books SET Email='lahlibra@gmail.com' WHERE ID=1 ;
DELETE FROM Books WHERE ID = 3;
TRUNCATE TABLE Books;
  ALTER TABLE Books ALTER COLUMN Author VARCHAR(5);
INSERT INTO Books(ID,BookTitle,Author,Year)
VALUES(4,'DARKSEEN','HARRY','2000-08-01');

ALTER TABLE Books ADD AuthorAddress VARCHAR(50) ,PUBLISHER VARCHAR(50);
DROP FROM Books WHERE AuthorAddress	  ;
ALTER TABLE Books DROP COLUMN AuthorAddress , PUBLISHER;

CREATE TABLE Author (
AuthorID INT PRIMARY KEY,
AuthorName VARCHAR(50),
EMAIL VARCHAR(50));
ALTER TABLE Books ADD 





